### ISSUE TITLE
Muon exercise 테스트

### ISSUE THREAD

**Issue by jhgoh** [cms-kr/CMSDAS#5]
현재 repository에 있는 예제를 NTU에서 동작하는지 확인
빠져 있는 부분인 muScaleFit 추가

**Comment by geonmo** [comment]
@jhgoh 특정 호스트인지 모든 호스트에서의 문제인지는 알 수 없으나 CMSSW_7_6_3_patch2 를 사용할 수 없는 머신들이 있습니다. 큰 문제가 없다면 CMSSW_7_5_7_patch2로 진행해보겠습니다.

**Comment by geonmo** [comment]
@jhgoh 비슷한 문제로 cmsRun을 돌려야 하는 Exercise4에서 에러가 납니다. 기본적은 CMSSW에러인 것으로 보이고 CVMFS 손상이 원인일 것으로 생각됩니다. 일단, 관련 내용으로 리포트를 했고 답변을 기다리는 중입니다.

**Comment by geonmo** [comment]
다음과 같은 에러 메세지입니다.

``` bash
----- Begin Fatal Exception 16-Feb-2016 00:31:06 CST-----------------------
An exception of category 'PluginLibraryLoadError' occurred while
   [0] Initializing either multi-threaded or single-threaded message logger
Exception Message:
unable to load /nas2/cmsdas/dasuser59/CMSSW_7_5_7_patch1/lib/slc6_amd64_gcc491/poisoned/plugin-poisoned-FWCoreMessageServicePlugins.so because /nas2/cmsdas/dasuser59/CMSSW_7_5_7_patch1/lib/slc6_amd64_gcc491/poisoned/plugin-poisoned-FWCoreMessageServicePlugins.so: cannot open shared object file: No such file or directory
----- End Fatal Exception -------------------------------------------------
```

임시적인 문제이기를 바랍니다만, 당일까지 해결이 안될 경우도 고민을 해야 할 거 같습니다.

**Comment by jhgoh** [comment]
cvmfs가 갱신되어 있지 않아 보여요. 제가 테스팅할 때도 마찬가지로 CMSSW_7_5_X 까지만 보이고 76X는 pre-release만 보여요 (ls /cvmfs/cms.cern.ch/cms/slc_/_) 저도 테스팅을 위해서는 75X에서 작업했어요.
뮤온에서 fwlite를 쓰기 때문에 버젼을 타지 않는데 top은 76X를 쓰게 했기 때문에 고쳐져야 돼요.

아래 에러는 git-cms-checkdeps -a 한 다음에 해보면 보통 해결되는데
하여간 바꿀 생각이라...

**Comment by geonmo** [comment]
@jhgoh 디렉토리 구조를 변경하셨나요? 현재 이렇게 구성하게되면

``` bash
CMSDAS2016
`-- MuonExercise
    `-- CMSSW_7_6_3_patch2
```

이런식으로 구성됩니다. 

CMSSW_7_6_3_patch2 - CMADAS2015 - MuonExercise 순으로 되는 것이 맞지 않나 생각됩니다.

그리고 git clone part가 없어졌네요. 의도하신 결과인지 궁금합니다.

**Comment by geonmo** [comment]
일단은 시간관계상 제가 맞다고 생각되는 방향으로 수정할테니 혹시 의도하신 결과라면 다시 수정해주세요^^

**Comment by geonmo** [comment]
CMSSW_7_6_3_patch2가 설치는 가능하나, 일부 서브 디렉토리의 권한이 잘못되어 있어서 작동을 안합니다.
내일 수업때까지 상태를 확인하고 안되면 FWLite 파트만 진행하는 것이 어떨까 하네요.

**Comment by jhgoh** [comment]
디렉토리 구조는 다시 바꿨어요. 특별한 의도가 있는 건 아니고 그냥 top 하고 같이 놓고 준비하다보니 편의상 그런거였어요.

muon exercise는 757로 가요. 76X에서는 git-cms-init이 안되네요.

mu scale fit은 fwlite으로 변경중.

**Comment by jhgoh** [comment]
mu scale 을 rochester correction으로 해서 구현 완료.

**Comment by jhgoh** [comment]
Change the twiki page to use 757 release. The exercise is not release dependent.
